export * from './News'
export * from './Home'
export * from './Teams'
export * from './Players'
export * from './ControlPanel/Login'
export * from './ControlPanel/Dashboard'
export * from './Championships'
